/** 많이 수정해야 합니다 */
class Artist {
    constructor(
        id,
        name,
        debut_date,
        birthdate,
        img_face,
        img_torso,
        img_banner,
        is_group,
        group_name,
    ) {
        this.id = id;
        this.name = name;
        this.debut_date = debut_date;
        this.birthdate = birthdate;
        this.img_face = img_face;
        this.img_torso = img_torso;
        this.img_banner = img_banner;
        this.is_group = is_group;
        this.group_name = group_name;
    }
}

/** 많이 수정해야 합니다 */
export const artistArray = [
    new Artist(
        1,
        "Jisoo",
        "20160808",
        "19950103",
        "",
        "",
        "",
        true,
        "BLACKPINK",
    ),
    new Artist(
        2,
        "Jennie",
        "20160808",
        "19960116",
        "",
        "",
        "",
        true,
        "BLACKPINK",
    ),
    new Artist(
        3,
        "Rosé",
        "20160808",
        "19970211",
        "",
        "",
        "",
        true,
        "BLACKPINK",
    ),
    new Artist(
        4,
        "Lisa",
        "20160808",
        "19970327",
        "",
        "",
        "",
        true,
        "BLACKPINK",
    ),
    new Artist(
        5,
        "Winter",
        "20201117",
        "20010101",
        "",
        "",
        "",
        true,
        "aespa",
    ),
    new Artist(
        6,
        "Karina",
        "20201117",
        "20000411",
        "",
        "",
        "",
        true,
        "aespa",
    ),
    new Artist(
        7,
        "Giselle",
        "20201117",
        "20001030",
        "",
        "",
        "",
        true,
        "aespa",
    ),
    new Artist(
        8,
        "Ningning",
        "20201117",
        "20021023",
        "",
        "",
        "",
        true,
        "aespa",
    ),
    new Artist(
        9,
        "RM",
        "20130613",
        "19940912",
        "",
        "",
        "",
        true,
        "BTS",
    ),
    new Artist(
        10,
        "Jin",
        "20130613",
        "19921204",
        "",
        "",
        "",
        true,
        "BTS",
    ),
    new Artist(
        11,
        "Suga",
        "20130613",
        "19930309",
        "",
        "",
        "",
        true,
        "BTS",
    ),
    new Artist(
        12,
        "J-Hope",
        "20130613",
        "19940218",
        "",
        "",
        "",
        true,
        "BTS",
    ),
    new Artist(
        13,
        "Jimin",
        "20130613",
        "19951013",
        "",
        "",
        "",
        true,
        "BTS",
    ),
    new Artist(
        14,
        "V",
        "20130613",
        "19951230",
        "",
        "",
        "",
        true,
        "BTS",
    ),
    new Artist(
        15,
        "Jungkook",
        "20130613",
        "19970901",
        "",
        "",
        "",
        true,
        "BTS",
    ),
    new Artist(16, "IU", "20080918", "19930516", "", "", "", false, undefined),
    new Artist(17, "Taeyeon", "20071005", "19890309", "", "", "", false, undefined),
    new Artist(18, "G-Dragon", "20060819", "19880818", "", "", "", false, undefined),
    new Artist(19, "Chungha", "20170607", "19960209", "", "", "", false, undefined),
    new Artist(20, "Sunmi", "20070205", "19920502", "", "", "", false, undefined),
];

/** 많이 수정해야 합니다 */
export const dummyAgencyUser = {
    id: 1,
    agencyName: "cool and awesome agency",
    managingArtistArray: artistArray,
    role: "admin",
};
